name: ROS-repos

on: [pull_request]

jobs:    
  # Lints repos specified in `ros2.repos` as well as repos already `src/`
  lint-repos:
    name: repos_ament_${{ matrix.linter }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          linter: [cppcheck, cpplint, uncrustify, lint_cmake, xmllint, flake8, pep257]
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Run linter
        run: |
          docker build -t $GITHUB_REPOSITORY -f ./.devcontainer/Dockerfile .
          docker run -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE -w $GITHUB_WORKSPACE $GITHUB_REPOSITORY \
          bash -c "
          vcs import --skip-existing < src/ros2.repos src \
          && ament_${{ matrix.linter }} src/
          "
          